name: Terraform Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '.github/workflows/terraform.yml'
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - '.github/workflows/terraform.yml'

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  terraform:
    uses: mtopps/github-workflows/.github/workflows/terraform-plan-apply.yml@v1.1.0
    secrets: inherit
    with:
      GCP_BUCKET_PREFIX: ${{ vars.GCP_BUCKET_PREFIX }}
      GCP_BUCKET: ${{ vars.GCP_BUCKET }}